local StrategyFactory = require("datamining.strategy_factories")

local TreasureStrategy = require("datamining.strategies.treasure")
local BossStrategy = require("datamining.strategies.boss")
local MinibossStrategy = require("datamining.strategies.miniboss")
local CurseStrategy = require("datamining.strategies.curse")
local ChallengeStrategy = require("datamining.strategies.challenge")
local BedroomStrategy = require("datamining.strategies.bedroom")
local ChestStrategy = require("datamining.strategies.chest")
local DiceStrategy = require("datamining.strategies.dice")

StrategyFactory.AddStrategyFactory(RoomType.ROOM_SHOP, TreasureStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_TREASURE, TreasureStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_BOSS, BossStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_MINIBOSS, MinibossStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_SECRET, TreasureStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_SUPERSECRET, TreasureStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_CURSE, CurseStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_CHALLENGE, ChallengeStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_LIBRARY, TreasureStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_DEVIL, CurseStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_ANGEL, TreasureStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_ISAACS, BedroomStrategy.CreateIsaacsStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_BARREN, BedroomStrategy.CreateBarrenStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_CHEST, ChestStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_DICE, DiceStrategy.CreateStrategy)
StrategyFactory.AddStrategyFactory(RoomType.ROOM_PLANETARIUM, TreasureStrategy.CreateStrategy)